FROM python:3.11-alpine

# Show print() output in docker logs
ENV PYTHONUNBUFFERED 1

RUN apk add --no-cache build-base \
  && apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/community librdkafka-dev

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt -t /app

ENTRYPOINT ["python", "consumer.py"]